name: 'Get and Cache Dependencies'
description: 'Get and Cache Dependencies'
inputs:
  force-install:
    description: 'Cache dependencies or force install'
    required: false
    default: 'false'
outputs:
  cache-used:
    description: 'Cache was used or not'
    value: ${{steps.install.outputs.cache}}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.force-install != 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.force-install != 'true'
      run: |
        npm ci
        echo "cache=${{inputs.force-install}}" >> $GITHUB_OUTPUT
      shell: bash