name: 'Get and Cache Dependencies'
description: 'Get and Cache Dependencies'
inputs:
  force-install:
    description: 'Cache dependencies or force install'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.force-install != 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.force-install != 'true'
      run: npm ci
      shell: bash