name: Deploy code
on:
  pull_request:
    types: [opened]
  workflow_dispatch:
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output data
        run: echo "${{toJson(github.event)}}"
      - name: Get code
        uses: actions/checkout@v3
      - name: InstallDependencies
        run: npm install
      - name: Run Test
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploy"
