name: Reusable
on: 
  workflow_call:
    inputs:
      artifact-name: 
        description: The name of the artifact to deploy
        required: false
        default: dist
        type: string
    secrets:
      some-secret:
          required: false
    outputs:
      result:
        description: Deploy results
        value: ${{jobs.deploy.outputs.outcomes}}
jobs:
  deploy:
    outputs:
      outcomes: ${{steps.result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: GetCode
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact-name}}
      - name: List files
        run: ls
      - name: Deploy
        run: echo "Deploy..." 
      - name: Set results
        id: result
        run: echo "step-result=success" >> $GITHUB_OUTPUT